Repository MJU-SDA-Backgate-Awsome-Guys/SDA-Project, pull requests merged in 2022-12, with the labels that each got.

#13 기온데이터 추가
  data/OBS_ASOS_TIM_20221204004425.csv
  data/OBS_ASOS_TIM_20221204004552.csv
  data/OBS_ASOS_TIM_20221204004614.csv
  data/OBS_ASOS_TIM_20221204004818.csv
  data/OBS_ASOS_TIM_20221204004958.csv
  data/OBS_ASOS_TIM_20221204005033.csv
  data/train.csv
  data/weather.csv
  data/날씨데이터.csv
  prepro.ipynb
  회의록/회의록2.md
Labels: ✅완료, 💻자료조사

#15 요일별&날짜별 식수인원 시각화
  .gitattributes
  EDA.ipynb
Labels: ✅완료

#14 다중공선성, 정규성 확인, Okt 이용 메뉴 단위로 분리
  Untitled.ipynb
  dataset/train.csv
Labels: 👨🏻‍💻작업중

#17 EDA (강수량에 따른 식수인원 시각화)
  EDA.ipynb
Labels: 👨🏻‍💻작업중

#21 test.csv 날씨데이터랑 합침
  data/test+weather.csv
  data/test.csv
  prepro.ipynb
Labels: ✅완료

#20 CountVectorizer를 활용한 one-hot encoding
  매뉴전처리.ipynb
  메뉴전처리.ipynb
Labels: ✅완료

#24 요일에 따른 식수 인원변화
  요일에따른식수인원변화.ipynb
Labels: ✅완료, 👀리뷰필요

#22 EDA (데이터 분포 확인, 컬럼별 식수인원 확인)
  EDA.ipynb
Labels: 👨🏻‍💻작업중
